import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AboutUsPage from '../views/aboutUsPage/aboutUsPage'


export default function AboutUs() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Borgfy</title>
        <meta name="description" content="Generated by Borgfy" />
        <link rel="icon" href="/logo_white.png" />
      </Head>

      <main>
        <AboutUsPage/>
      </main>

      
    </div>
  )
}
