import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BlogDetailPage from '../views/blogDetailPage/blogDetailPage'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Borgfy</title>
        <meta name="description" content="Generated by Borgfy" />
        <link rel="icon" href="/logo_white.png" />
      </Head>

      <main>
        <BlogDetailPage/>
      </main>

      
    </div>
  )
}
