import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BlogDetailPage from '../views/blogDetailPage/blogDetailPage'
import BrainPage from '../views/brainPage/brainPage'


export default function BrainStorm() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <BrainPage/>
      </main>

      
    </div>
  )
}
