import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Case from '../views/casePage/case'



export default function Case2() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Case/>
      </main>

      
    </div>
  )
}
