import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ContactPage from '../views/contactPage/contactPage'



export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Borgfy</title>
        <meta name="description" content="Generated by Borgfy" />
        <link rel="icon" href="/logo_white.png" />
      </Head>

      <main>
        <ContactPage/>
      </main>

      
    </div>
  )
}
