import Head from 'next/head'
import styles from '../styles/Home.module.css'
import DynamicCasePage from '../views/dynamicCasePage/case'

export default function DynamicCases() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DynamicCasePage/>
      </main>

      
    </div>
  )
}
