import Head from 'next/head'
import styles from '../styles/Home.module.css'
import DynamicBlogsPage from '../views/dynamicBlogsPags/blogsPage'
import DynamicCasePage from '../views/dynamicCasePage/case'

export default function DynamicBlogs() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Borgfy - Shaping Visions</title>
        <meta name="description" content="Generated by Borgfy" />
        <link rel="icon" href="/tab_icon.png" />
      </Head>

      <main>
        <DynamicBlogsPage/>
      </main>

      
    </div>
  )
}
