import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Landing2Page from '../views/landing2Page/landing2Page'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Borgfy - Shaping Visions</title>
        <meta name="description" content="Generated by Borgfy" />
        <link rel="icon" href="/tab_icon.png" />
      </Head>

      <main>
        <Landing2Page/>
      </main>

      
    </div>
  )
}
