import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Landing2Page from '../views/landing2Page/landing2Page'

export default function Landing2() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Landing2Page/>
      </main>

      
    </div>
  )
}
