import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import styles from '../../styles/Home.module.css'
import DynamicBlogDetailPage from '../../views/dynaicBlogDetailPage/blogDetailPage'
import DynamicCaseStudyPage from '../../views/dynamicCaseStudyPage/caseStudyPage'

export default function DynamicBlog() {

    const router = useRouter()

    const [useCase, setUseCase] = useState()

    useEffect(() => {
        const { id } = router.query
        axios.get(`https://admin.borgfy.com/blogs/${id}`)
        .then((res)=>{
            setUseCase(res.data[0])
        })
        .catch((err)=>{
            alert("Some Error Occured While Fetching Blogs")
        })
    }, [])
    


  return (
    <div className={styles.container}>
      <Head>
        <title>Borgfy</title>
        <meta name="description" content="Generated by Borgfy" />
        <link rel="icon" href="/logo_white.png" />
      </Head>

      <main>
        <DynamicBlogDetailPage blog = {useCase} />
      </main>

      
    </div>
  )
}
