import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import styles from '../../styles/Home.module.css'
import DynamicCaseStudyPage from '../../views/dynamicCaseStudyPage/caseStudyPage'

export default function DynamicCase() {

    const router = useRouter()

    const [useCase, setUseCase] = useState()

    useEffect(() => {
        const { id } = router.query
        axios.get(`http://localhost:3000/cases/${id}`)
        .then((res)=>{
            setUseCase(res.data[0])
        })
        .catch((err)=>{
            alert("Some Error Occured While Fetching Use Case")
        })
    }, [])
    


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DynamicCaseStudyPage useCase = {useCase}/>
      </main>

      
    </div>
  )
}
